<section class="mt-6 rounded-2xl border border-slate-200 bg-white p-4 shadow-sm sm:p-6">
    <div class="flex flex-col gap-2 sm:flex-row sm:items-end sm:justify-between">
        <div><p class="text-xs font-semibold uppercase tracking-[0.16em] text-indigo-600">Revisión por jornada</p><h2 class="mt-1 text-xl font-black text-slate-950">Autorizaciones de horas extra</h2><p class="mt-1 max-w-3xl text-sm text-slate-600">El sistema calcula el tramo completo fuera de la jornada asignada. Una decisión humana determina si ese tiempo será pagable.</p></div>
        <p class="text-sm font-semibold text-slate-700">{{ $overtimeRows->total() }} candidatos</p>
    </div>
    <div class="mt-5 rounded-2xl border border-slate-200 bg-slate-50 p-4">
        <p class="text-sm font-bold text-slate-900">Filtrar autorizaciones</p>
        <div class="mt-3 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">
            <label class="text-xs font-semibold text-slate-600">Empleado o código<input wire:model.live.debounce.300ms="overtimeSearch" type="search" class="mt-1 w-full rounded-lg border-slate-300 text-sm"></label>
            <label class="text-xs font-semibold text-slate-600">Estado<select wire:model.live="overtimeStatus" class="mt-1 w-full rounded-lg border-slate-300 text-sm"><option value="pending">Pendientes</option><option value="approved">Aprobados</option><option value="rejected">Rechazados</option><option value="all">Todos</option></select></label>
            <label class="text-xs font-semibold text-slate-600">Fecha laboral<input wire:model.live="overtimeDate" type="date" class="mt-1 w-full rounded-lg border-slate-300 text-sm"></label>
            <label class="text-xs font-semibold text-slate-600">Porcentaje<select wire:model.live="overtimeRate" class="mt-1 w-full rounded-lg border-slate-300 text-sm"><option value="">Todos</option><option value="ordinary">Ordinario</option><option value="extra25">25%</option><option value="extra50">50%</option><option value="extra75">75%</option><option value="extra100">100%</option></select></label>
        </div>
        @if ($overtimeStatus === 'pending' || $overtimeStatus === 'all')
            <div class="mt-3 flex flex-wrap items-center gap-2"><button type="button" wire:click="selectCurrentOvertimePage" class="rounded-lg border border-indigo-300 bg-white px-3 py-2 text-xs font-bold text-indigo-700">Seleccionar esta página</button>@if (!$allFilteredOvertimeSelected && $selectedOvertimeCandidates && $pendingOvertimeMatchCount > count($selectedOvertimeCandidates))<button type="button" wire:click="selectAllFilteredOvertime" class="rounded-lg bg-indigo-600 px-3 py-2 text-xs font-bold text-white">Seleccionar los {{ $pendingOvertimeMatchCount }} resultados</button>@endif @if ($allFilteredOvertimeSelected || $selectedOvertimeCandidates)<button type="button" wire:click="clearOvertimeSelection" class="rounded-lg px-3 py-2 text-xs font-bold text-slate-600">Limpiar selección</button>@endif</div>
            @error('selectedOvertimeCandidates') <p class="mt-2 text-sm text-rose-700">{{ $message }}</p> @enderror
        @endif
    </div>
    <div class="mt-5 space-y-4">
        @forelse ($overtimeGroups as $group)
            <details wire:key="overtime-employee-{{ $group['employee']->id }}" class="overflow-hidden rounded-2xl border border-slate-200 bg-slate-50"><summary class="flex cursor-pointer list-none items-center justify-between gap-4 bg-white px-4 py-3"><div><p class="font-bold text-slate-950">{{ $group['employee']->full_name }}</p><p class="text-xs text-slate-500">Código {{ $group['employee']->external_id }}</p></div><p class="text-right text-sm font-semibold text-slate-700">{{ $group['rows']->count() }} candidatos · {{ $group['minutes'] }} min</p></summary>
                <div class="space-y-3 border-t border-slate-200 p-4">
                    @foreach ($group['rows'] as $row)
                        @php($review = $row['review']) @php($candidate = $row['candidate']) @php($decision = $row['decision']) @php($selectionToken = implode('|', [$review->employee->id, $review->analysis->workDate->toDateString(), $candidate->key]))
                        <div class="rounded-xl border border-slate-200 bg-white p-4"><div class="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between">
                            <div>@if (!$decision)<label class="flex shrink-0 items-center gap-2 text-xs font-bold text-slate-700"><input type="checkbox" @if ($allFilteredOvertimeSelected) checked disabled @else wire:model.live="selectedOvertimeCandidates" value="{{ $selectionToken }}" @endif class="rounded border-slate-300 text-indigo-600">Seleccionar candidato</label>@endif
                                <p class="mt-2 text-sm font-bold text-slate-950">{{ match ($candidate->kind) { 'pre_shift' => 'Entrada anterior', 'post_shift' => 'Salida posterior', 'non_working' => 'Día no laborable', default => 'Tramo fuera de jornada' } }}</p><p class="mt-1 text-sm font-semibold text-slate-700">Fecha laboral {{ $review->analysis->workDate->format('d/m/Y') }}</p><p class="mt-1 text-sm text-slate-600">{{ $candidate->start->format('d/m H:i') }} → {{ $candidate->end->format('d/m H:i') }}</p><p class="mt-1 text-xs text-slate-500">Jornada asignada {{ $review->occurrence->scheduledStart?->format('H:i') ?? '—' }} → {{ $review->occurrence->scheduledEnd?->format('H:i') ?? '—' }} · Marcas de asistencia {{ $review->analysis->entryAt?->format('H:i') ?? '—' }} → {{ $review->analysis->exitAt?->format('H:i') ?? '—' }}</p><p class="mt-1 text-sm font-semibold text-slate-800">{{ $candidate->minutes }} min{{ $review->analysis->payrollPolicyKey === \App\Models\WorkScheduleProfilePublication::DURATION_FIRST_V2 ? ' detectados' : '' }} · {{ number_format($candidate->minutes / 60, 2, ',', '.') }} h</p>
                                @if ($review->analysis->excludedTransferMinutes > 0)<p class="mt-1 text-xs font-semibold text-sky-800">{{ $review->analysis->excludedTransferMinutes }} min de traslado excluidos</p>@endif
                                <p class="mt-1 text-xs text-slate-500">{{ collect(['Ordinario' => $candidate->rateMinutes->ordinaryMinutes, '25%' => $candidate->rateMinutes->extra25Minutes, '50%' => $candidate->rateMinutes->extra50Minutes, '75%' => $candidate->rateMinutes->extra75Minutes, '100%' => $candidate->rateMinutes->extra100Minutes])->filter()->map(fn ($minutes, $rate) => $rate.': '.$minutes.' min')->implode(' · ') }}</p>
                            </div><div class="flex max-w-sm flex-col items-start gap-2 sm:items-end">@if ($decision)<div class="rounded-xl border px-3 py-2 text-sm {{ $decision->decision === 'approved' ? 'border-emerald-200 bg-emerald-50 text-emerald-950' : 'border-rose-200 bg-rose-50 text-rose-950' }}"><p class="font-bold">{{ $decision->decision === 'approved' ? 'Aprobado' : 'Rechazado' }}</p>@if ($decision->resolution_kind === 'partial')<p class="mt-1">{{ $decision->approved_minutes }} min aprobados · {{ $decision->rejected_minutes }} min rechazados</p>@endif<p class="mt-1">{{ $decision->reason }}</p><p class="mt-1 text-xs opacity-80">{{ $decision->decider->email ?: 'Usuario eliminado' }} · {{ $decision->created_at?->format('d/m/Y H:i') }}</p></div>@else<span class="inline-flex rounded-full bg-amber-100 px-3 py-1 text-xs font-bold text-amber-900">Pendiente de decisión</span>@endif
                                <div class="flex flex-wrap gap-2"><x-ui.loading-button type="button" wire:click="openOvertimeDecision({{ $review->employee->id }}, '{{ $review->analysis->workDate->toDateString() }}', '{{ $candidate->key }}', 'approved', '{{ $candidate->start->format('H:i') }} → {{ $candidate->end->format('H:i') }} · {{ $candidate->minutes }} min', '{{ $candidate->start->format('Y-m-d\TH:i') }}', '{{ $candidate->end->format('Y-m-d\TH:i') }}')" loading-label="Abriendo…" :disabled="$isBlocked || $decision?->decision === 'approved'" class="rounded-lg bg-emerald-600 px-3 py-2 text-xs font-bold text-white disabled:opacity-40">Aprobar completo</x-ui.loading-button><x-ui.loading-button type="button" wire:click="openOvertimeDecision({{ $review->employee->id }}, '{{ $review->analysis->workDate->toDateString() }}', '{{ $candidate->key }}', 'rejected', '{{ $candidate->start->format('H:i') }} → {{ $candidate->end->format('H:i') }} · {{ $candidate->minutes }} min', '{{ $candidate->start->format('Y-m-d\TH:i') }}', '{{ $candidate->end->format('Y-m-d\TH:i') }}')" loading-label="Abriendo…" :disabled="$isBlocked || $decision?->decision === 'rejected'" class="rounded-lg border border-rose-300 bg-white px-3 py-2 text-xs font-bold text-rose-700 disabled:opacity-40">Rechazar completo</x-ui.loading-button>@if ($review->analysis->payrollPolicyKey === \App\Models\WorkScheduleProfilePublication::DURATION_FIRST_V2)<x-ui.loading-button type="button" wire:click="openOvertimeDecision({{ $review->employee->id }}, '{{ $review->analysis->workDate->toDateString() }}', '{{ $candidate->key }}', 'partial', '{{ $candidate->start->format('H:i') }} → {{ $candidate->end->format('H:i') }} · {{ $candidate->minutes }} min', '{{ $candidate->start->format('Y-m-d\TH:i') }}', '{{ $candidate->end->format('Y-m-d\TH:i') }}')" loading-label="Abriendo…" :disabled="$isBlocked" class="rounded-lg border border-indigo-300 bg-white px-3 py-2 text-xs font-bold text-indigo-700 disabled:opacity-40">Aprobar parcialmente</x-ui.loading-button>@endif</div>
                            </div></div></div>
                    @endforeach
                </div>
            </details>
        @empty <div class="rounded-xl border border-dashed border-slate-300 bg-slate-50 px-4 py-8 text-center"><p class="font-semibold text-slate-800">No hay candidatos de hora extra con el filtro actual.</p><p class="mt-1 text-sm text-slate-500">Las marcas dentro de la jornada asignada no requieren autorización.</p></div>
        @endforelse
    </div>
    @if ($overtimeRows->hasPages())<div class="mt-5">{{ $overtimeRows->links() }}</div>@endif
    @if ($allFilteredOvertimeSelected || $selectedOvertimeCandidates)<div class="sticky bottom-4 z-30 mt-5 flex flex-wrap items-center justify-between gap-3 rounded-2xl bg-slate-950 px-4 py-3 text-white shadow-xl"><p class="text-sm font-bold">{{ $allFilteredOvertimeSelected ? $pendingOvertimeMatchCount : count($selectedOvertimeCandidates) }} seleccionados</p><div class="flex gap-2"><x-ui.loading-button type="button" wire:click="openOvertimeBatch('approved')" loading-label="Abriendo…" :disabled="$isBlocked" class="rounded-lg bg-emerald-600 px-4 py-2 text-sm font-bold disabled:opacity-40">Aprobar</x-ui.loading-button><x-ui.loading-button type="button" wire:click="openOvertimeBatch('rejected')" loading-label="Abriendo…" :disabled="$isBlocked" class="rounded-lg bg-rose-600 px-4 py-2 text-sm font-bold disabled:opacity-40">Rechazar</x-ui.loading-button></div></div>@endif
    @if ($showOvertimeBatchModal)<div class="fixed inset-0 z-50 flex items-center justify-center bg-slate-900/50 p-4"><div role="dialog" aria-modal="true" class="w-full max-w-lg rounded-2xl bg-white p-5 shadow-xl"><p class="text-xs font-semibold uppercase tracking-[0.16em]">Decisión masiva auditada</p><h2 class="mt-1 text-xl font-black text-slate-950">{{ $overtimeBatchDecision === 'approved' ? 'Aprobar candidatos seleccionados' : 'Rechazar candidatos seleccionados' }}</h2><p class="mt-2 rounded-xl bg-slate-100 px-3 py-2 text-sm font-bold text-slate-800">Se procesarán exactamente {{ $overtimeBatchCount }} candidatos pendientes.</p><p class="mt-2 text-xs text-slate-600">{{ $overtimeBatchFilterSummary }}</p><form wire:submit="submitOvertimeBatch" class="mt-4 space-y-4"><textarea wire:model="overtimeBatchReason" rows="3" maxlength="500" class="w-full rounded-xl border border-slate-300" placeholder="Este motivo quedará registrado en cada decisión"></textarea>@error('overtimeBatchReason')<p class="text-sm text-rose-700">{{ $message }}</p>@enderror @error('selectedOvertimeCandidates')<p class="text-sm text-rose-700">{{ $message }}</p>@enderror <div class="flex justify-end gap-2"><button type="button" wire:click="closeOvertimeBatchModal">Cancelar</button><x-ui.loading-button type="submit" target="submitOvertimeBatch" loading-label="Enviando…" :disabled="$isBlocked">Confirmar lote</x-ui.loading-button></div></form></div></div>@endif
    @if ($showOvertimeDecisionModal)<div class="fixed inset-0 z-50 flex items-center justify-center bg-slate-900/50 p-4"><div class="w-full max-w-lg rounded-2xl bg-white p-5 shadow-xl"><p class="text-xs font-semibold uppercase tracking-[0.16em]">Decisión auditada</p><h2 class="mt-1 text-xl font-black text-slate-950">{{ match ($overtimeDecision) { 'approved' => 'Aprobar tramo completo', 'rejected' => 'Rechazar tramo completo', default => 'Aprobar tramo parcial' } }}</h2><p class="mt-2 rounded-xl bg-slate-100 px-3 py-2 text-sm font-bold text-slate-800">{{ $overtimeCandidateSummary }}</p><p class="mt-3 text-sm text-slate-600">{{ $overtimeDecision === 'partial' ? 'Seleccione un subintervalo exacto. El sistema rechazará el complemento y conservará todas las bandas.' : 'La duración fue calculada por el sistema. Si cambian las marcas o la jornada, esta decisión deja de ser vigente.' }}</p><form wire:submit="submitOvertimeDecision" class="mt-4 space-y-4">@if ($overtimeDecision === 'partial')<div class="grid gap-3 sm:grid-cols-2"><input type="datetime-local" wire:model="overtimeApprovedStartsAt" class="rounded-xl border-slate-300"><input type="datetime-local" wire:model="overtimeApprovedEndsAt" class="rounded-xl border-slate-300"></div>@error('overtimeApprovedStartsAt')<p class="text-sm text-rose-700">{{ $message }}</p>@enderror @error('overtimeApprovedEndsAt')<p class="text-sm text-rose-700">{{ $message }}</p>@enderror @endif<textarea wire:model="overtimeDecisionReason" rows="3" maxlength="500" class="w-full rounded-xl border-slate-300" placeholder="Motivo obligatorio"></textarea>@error('overtimeDecisionReason')<p class="text-sm text-rose-700">{{ $message }}</p>@enderror <div class="flex justify-end gap-2"><button type="button" wire:click="closeOvertimeDecisionModal">Cancelar</button><button type="submit">Confirmar</button></div></form></div></div>@endif
    <span class="sr-only" wire:loading wire:target="submitOvertimeDecision">Enviando decisión…</span>
</section>
